FAP/Controllers/ScheduleController.cs
using FAP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Globalization;

namespace FAP.Controllers
{
    public class ScheduleController : Controller
    {
        private readonly ProjectPRNContext _context;

        public ScheduleController(ProjectPRNContext context)
        {
            _context = context;
        }

        private DateTime GetStartDateOfWeek(int weekNumber, int year)
        {
            DateTime startDate = new DateTime(year, 1, 1);
            int daysToFirstDay = (int)startDate.DayOfWeek - (int)DayOfWeek.Monday;
            startDate = startDate.AddDays(-daysToFirstDay);

            int daysToAdd = (weekNumber - 1) * 7;
            DateTime startDateOfWeek = startDate.AddDays(daysToAdd);

            return startDateOfWeek;
        }

        private int getWeekNum(DateTime date)
        {
            return CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(date, CalendarWeekRule.FirstDay, DayOfWeek.Sunday);
        }

        public IActionResult Index(int week, int year)
        {
            if (HttpContext.Session.GetString("UserId") !=  null)
            {
                if (year == 0)
                    year = DateTime.Now.Year;

                if (week == 0)
                {
                    if (year == DateTime.Now.Year)
                        week = getWeekNum(DateTime.Now);
                    else
                        week = 1;
                }

                var slots = _context.Slots.ToList();
                ViewBag.slots = slots;

                DateTime startDate = GetStartDateOfWeek(week, year);

                ViewBag.weekNumber = week;
                ViewBag.year = year;
                ViewBag.startDate = startDate;

                List<ClassSchedule> classSchedule;
                List<Class> listClass = new List<Class>();

                string userCode = HttpContext.Session.GetString("UserId");

                if (HttpContext.Session.GetString("UserRole") == "Teacher")
                {
                    classSchedule = _context.ClassSchedules
                    .Where(cs => cs.Class.TeacherCode == userCode && cs.Date.Date >= startDate && cs.Date.Date <= startDate.AddDays(6))
                    .ToList();

                    listClass = _context.Classes
                        .Where(c => c.TeacherCode == userCode)
                        .ToList();
                } else
                {
                    classSchedule = _context.ClassSchedules
                    .Where(cs => cs.ClassId == 1 && cs.Date.Date >= startDate && cs.Date.Date <= startDate.AddDays(6))
                    .ToList();
                }

                ViewBag.listClass = listClass;

                return View(classSchedule);
            }
            else
            {
                return Redirect("Home");
            }
        }

        public IActionResult ChangeSchedule()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ChangeSchedule(int currentClass, DateTime currentDate, int currentSlot, DateTime moveDate, int moveSlot)
        {
            Request req = new Request()
            {
                ClassId = currentClass,
                FromDate = currentDate,
                ToDate = moveDate,
                FromSlotId = currentSlot,
                ToSlotId = moveSlot,
                SendBy = HttpContext.Session.GetString("UserId")
            };

			_context.Requests.Add(req);
			_context.SaveChanges();

			return RedirectToAction("Index");
        }

        public IActionResult ListRequest()
        {
            if (HttpContext.Session.GetString("UserRole") == "Manager")
            {
                List<Request> listReq = _context.Requests.ToList();
                return View(listReq);
            }
            else
            {
                return Redirect("Home");
            }
        }

        public IActionResult updateStatus(int id, int status)
        {
			if (HttpContext.Session.GetString("UserRole") == "Manager")
			{
				Request req = _context.Requests.FirstOrDefault(r => r.Id == id);

                if (status == 1)
                {
					ClassSchedule schedule = _context.ClassSchedules
					.FirstOrDefault(cs => cs.ClassId == req.ClassId && cs.Date == req.FromDate && cs.SlotId == req.FromSlotId);

					schedule.Date = req.ToDate;
					schedule.SlotId = req.ToSlotId;

					_context.ClassSchedules.Update(schedule);
				}
                
				req.Status = status;

                _context.Requests.Update(req);
                _context.SaveChanges();

                return Redirect("ListRequest");
			}
			else
			{
				return Redirect("Home");
			}
		}
    }
}

FAP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FAP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FAP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://seeklogo.com/images/F/fpt-university-logo-B3B6D84292-seeklogo.com.png" height="40" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Schedule" asp-action="Index">Schedule</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="~/Home/Logout">Sign out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FAP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>